routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');
});
Route::post('/',function (){
    $query = Request::input('search');

    $students = \App\Student::where('stud_name', 'LIKE', '%' . $query . '%')->get();

    var_dump('search result');

    foreach ($students as $student){
        var_dump($student->stud_name);
    }
});

Route::put('/', function (){

});



Auth::routes();

Route::resource('students','StudentController');
Route::resource('books','BookController');
Route::resource('borrows','BorrowController');
Route::get('borrows/{borrow}/extend','BorrowController@extend')->name('borrows.extend');
Route::put('borrows/{borrow}','BorrowController@returned')->name('borrows.returned');
Route::get('getname/{borrow}', 'BorrowController@getname');
Route::resource('returns','ReturnController');
Route::resource('extends','ExtendController');
Route::get('/home', 'HomeController@index')->name('home');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = ['firstname','lastname','student_id','gender','year'];

    public function books() {
        return $this->hasMany('App\Book','student_id','id');
    }
    public function borrow() {
        return $this->belongsTo('App\Borrow','id');
    }

   /* public function year() {
      return $this->hasOne('App\Year','student_id');
}*/

}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Year;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Input;
use UxWeb\SweetAlert;
use App\Book;
use App\Http\Requests\StudentRequest;
use App\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StudentController extends Controller


{
    public function __construct(Student $students)
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::select('student_id', DB::raw('CONCAT(firstname, " ", lastname) AS name, id, gender, year'))->get();
        return view('students.index',compact('students'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentRequest $request)
    {
        $students = Student::create($request->all());
        /*$year = new Year;
        $year->year = Input::get('year');
        $students->year()->save($year);*/
        return redirect()->route('students.index')->with('message','Student has been added succesfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Res ponse
     */
    public function show( Student $student, Book $books)
    {
        //$books = DB::table('books')->get();
        //$books = \App\Book::find($student->books);
        //$books->update(($request->input('student_id')));
        //$student = Student::select('student_id', DB::raw('CONCAT(firstname, " ", lastname) AS name, id'))->get();
        $books = \App\Book::where('student_id','=',$student->student_id)->get();
        return view('students.show',compact('student','books'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('students.edit',compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StudentRequest $request, Student $student)
    {

        $student->update(($request->all()));
        return redirect()->route('students.index')->with('message','Student has been updated succesfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('students.index')->with('message','Student has been deleted succesfully');
    }


}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @if(Session::has('message'))
                    <div class="alert alert-success">{{ Session::get('message') }}</div>
                @endif

                <div class="panel panel-default">

                    <div class="panel-heading">Add Student</div>

                    <div class="panel-body">
                        {!! Form::open(array('route'=>'students.store')) !!}
                            <div class="col-xs-12">
                                <div class="form-group">
                                    {!! Form::label('student_id','Enter student id') !!}
                                    {!! Form::number('student_id',null,['class'=>'form-control','placeholder'=>'Enter Student Id']) !!}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    {!! Form::label('firstname','Enter First Name') !!}
                                    {!! Form::text('firstname',null,['class'=>'form-control','placeholder'=>'Enter First Name']) !!}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    {!! Form::label('lastname','Enter Last Name') !!}
                                    {!! Form::text('lastname',null,['class'=>'form-control','placeholder'=>'Enter Last Name']) !!}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    {!! Form::label('gender','Gender') !!}
                                    <select class="form-control">
                                        <option disabled="disabled" selected="selected">Gender</option>
                                        <option>Male</option>
                                        <option>Female</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    {!! Form::label('year','Enter student year/section') !!}
                                    {!! Form::text('year',null,['class'=>'form-control','placeholder'=>'Enter Student Year & Section']) !!}
                                </div>
                            </div>

                        <div class="col-md-2">
                            <div class="form-group">
                                {!! Form::button('Add student',['type'=>'submit','class'=>'btn btn-primary']) !!}
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
                    @if($errors->all())
                        <ul class="alert alert-danger">
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif
            </div>

            </div>
        </div>
    </div>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">

                    <div class="panel-heading">Student</div><br>
                    <div class="panel-body">
                        {!! Form::model($student,array('route'=>['students.update',$student->id],'method'=>'PUT')) !!}
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        {!! Form::label('student_id','Enter student id') !!}
                                        {!! Form::number('student_id',null,['class'=>'form-control','placeholder'=>'Enter Student Id']) !!}
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        {!! Form::label('firstname','Enter First Name') !!}
                                        {!! Form::text('firstname',null,['class'=>'form-control','placeholder'=>'Enter First Name']) !!}
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        {!! Form::label('lastname','Enter Last Name') !!}
                                        {!! Form::text('lastname',null,['class'=>'form-control','placeholder'=>'Enter Last Name']) !!}
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        {!! Form::label('gender','Gender') !!}
                                        <select class="form-control" selected="{{  $student->gender }}">
                                            <option disabled="disabled">Gender</option>
                                            <option>Male</option>
                                            <option>Female</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        {!! Form::label('year','Enter student year/section') !!}
                                        {!! Form::text('year',null,['class'=>'form-control','placeholder'=>'Enter Student Year & Section']) !!}
                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                        {!! Form::button('Add student',['type'=>'submit','class'=>'btn btn-primary']) !!}
                                    </div>
                                </div>
                        {!! Form::close() !!}
                    </div>
                </div>
                    @if($errors->all())
                        <ul class="alert alert-danger">
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif
            </div>
        </div>
    </div>
@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @if(Session::has('message'))
                    <div class="alert alert-success">{{ Session::get('message') }}</div>
                @endif

                <div class="panel panel-default">

                    <div class="panel-heading">Student</div><br>
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ link_to_route('students.create','Add new student',null,['class'=>'btn btn-primary']) }}

                        </div>
                    </div>

                    <div class="panel-body">

                        <table class="table">
                            <tr>
                                <th>Student ID</th>
                                <th>Student Name</th>
                                <th>Gender</th>
                                <th>Year/Section</th>
                                <th>Action</th>
                            </tr>

                            @foreach($students as $student)
                                <tbody>
                                <tr>
                                    <td>{{ link_to_route('students.show',$student->student_id,$student->id) }}</td>
                                    <td>{{ link_to_route('students.show',$student->name,$student->id) }}</td>
                                    <td>{{ link_to_route('students.show',$student->gender,$student->id) }}</td>
                                    <td>{{ link_to_route('students.show',$student->year,$student->id) }}</td>
                                    <td>
                                        {!! Form::open(array('route'=>['students.destroy',$student->id],'method'=>'DELETE')) !!}
                                        {{ link_to_route('students.edit','Edit',[$student->id],['class'=>'btn btn-primary']) }}
                                        |
                                        {!! Form::button('Delete',['class'=>'btn btn-danger','type'=>'submit']) !!}
                                        {!!  Form::close() !!}
                                    </td>

                                </tr>
                                </tbody>
                            @endforeach
                        </table>


                    </div>
                </div>

            </div>
        </div>
    </div>


@endsection

<script>
    function search() {
        $('form input:text').keyup(function () {
            $value=$(this).val();
            $.ajax({
                type : 'get',
                url : '{{URL::to('search')}}',
                data : {'search':$value},
                success:function (data) {
                    alert(data);
                    //$('tbody').html(data);

                }
            })
        })
    }

</script>

resources/views/students/return.blade.php
@extends('layouts.app')
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @if(Session::has('message'))
                    <div class="alert alert-success">{{ Session::get('message') }}</div>
                @endif

                <div class="panel panel-default">

                    <div class="panel-heading">Student</div><br>
                    <div class="panel-body">

                        {!! Form::model($student,array('route'=>['students.update',$student->id],'method'=>'PUT')) !!}
                        <div class="col-xs-12">
                            <div class="form-group">
                                {!! Form::label('stud_id','Enter student id') !!}
                                {!! Form::number('stud_id',null,['class'=>'form-control']) !!}
                            </div>
                        </div>

                        <div class="col-xs-12">
                            <div class="form-group">
                                {!! Form::label('stud_name','Enter student name') !!}
                                {!! Form::text('stud_name',null,['class'=>'form-control']) !!}
                            </div>
                        </div>

                        <div class="col-xs-12">
                            <div class="form-group">
                                {!! Form::label('stud_yr','Enter student year/section') !!}
                                {!! Form::text('stud_yr',null,['class'=>'form-control']) !!}
                            </div>
                        </div>

                        <div class="col-md-2">
                            <div class="form-group">
                                {!! Form::button('Update student',['type'=>'submit','class'=>'btn btn-primary']) !!}
                            </div>
                        </div>
                        {!! Form::close() !!}

                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/students/show.blade.php
@extends('layouts.app')
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                @if(Session::has('message'))
                    <div class="alert alert-success">{{ Session::get('message') }}</div>
                @endif

                <div class="panel panel-default">

                    <div class="panel-heading">Student</div><br>
                    <div class="panel-body">


                        Student Id : {{ link_to_route('students.show',$student->student_id,$student->id) }}<br>
                        Student First Name : {{ link_to_route('students.show',$student->firstname,$student->id) }}<br>
                        Student Last Name : {{ link_to_route('students.show',$student->lastname,$student->id) }}<br>
                        Student Year/Section : {{ link_to_route('students.show',$student->year,$student->id) }}<br><br>
                        <p><h3>Student Borrowed books:</h3></p>

                                        <table class="table">
                                            <tr>
                                                <th>Book Code</th>
                                                <th>Book Name</th>
                                                <th>Book Description</th>
                                                <th>Book Author</th>
                                                <th>Book Release</th>
                                            </tr>

                                                @foreach ($books as $book)
                                                    <tr>
                                                        <td>{{ link_to_route('books.show',$book->isbn,$book->id) }}</td>
                                                        <td>{{ $book->b_name }}</td>
                                                        <td>{{ $book->b_des }}</td>
                                                        <td>{{ $book->b_aut }}</td>
                                                        <td>{{ $book->b_year }}</td>
                                                        </tr>
                                                @endforeach




                                        </table>


                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection